apiVersion: v1
kind: Pod
spec:
  volumes:
  - name: jenkins-docker-sock
    hostPath:
      path: /var/run/docker.sock
  containers:
  - name: docker
    image: docker
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: jenkins-docker-sock
    command:
    - cat
    tty: true
